// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// AutoEventManager is an autogenerated mock type for the AutoEventManager type
type AutoEventManager struct {
	mock.Mock
}

// RestartForDevice provides a mock function with given fields: name
func (_m *AutoEventManager) RestartForDevice(name string) {
	_m.Called(name)
}

// StartAutoEvents provides a mock function with given fields:
func (_m *AutoEventManager) StartAutoEvents() {
	_m.Called()
}

// StopForDevice provides a mock function with given fields: name
func (_m *AutoEventManager) StopForDevice(name string) {
	_m.Called(name)
}

type mockConstructorTestingTNewAutoEventManager interface {
	mock.TestingT
	Cleanup(func())
}

// NewAutoEventManager creates a new instance of AutoEventManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAutoEventManager(t mockConstructorTestingTNewAutoEventManager) *AutoEventManager {
	mock := &AutoEventManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
