// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	interfaces "github.com/edgexfoundry/app-functions-sdk-go/v2/pkg/interfaces"
	mock "github.com/stretchr/testify/mock"
)

// BackgroundPublisher is an autogenerated mock type for the BackgroundPublisher type
type BackgroundPublisher struct {
	mock.Mock
}

// Publish provides a mock function with given fields: payload, context
func (_m *BackgroundPublisher) Publish(payload []byte, context interfaces.AppFunctionContext) error {
	ret := _m.Called(payload, context)

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte, interfaces.AppFunctionContext) error); ok {
		r0 = rf(payload, context)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
